import "../globals.css";
import localFont from 'next/font/local'
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ReactLenis } from '@/utils/lenis';

const helveticaFont = localFont({
  src: [
    {
      path: "../../fonts/HelveticaNowText-Thin.woff2",
      weight: "100",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-ThinItalic.woff2",
      weight: "100",
      style: 'italic',
    },
    {
      path: "../../fonts/HelveticaNowText-ExtraLight.woff2",
      weight: "200",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-Light.woff2",
      weight: "300",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-LightItalic.woff2",
      weight: "300",
      style: 'italic',
    },
    {
      path: "../../fonts/HelveticaNowText-Regular.woff2",
      weight: "400",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-Medium.woff2",
      weight: "500",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-MediumItalic.woff2",
      weight: "500",
      style: 'italic',
    },
    {
      path: "../../fonts/HelveticaNowText-Bold.woff2",
      weight: "700",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-ExtraBold.woff2",
      weight: "800",
      style: 'normal',
    },
    {
      path: "../../fonts/HelveticaNowText-Black.woff2",
      weight: "900",
      style: 'normal',
    },
  ],
  variable: "--font-helvetica"
})

const marcellusFont = localFont({
  src: [
    {
      path: "../../fonts/Marcellus-Regular.woff2",
      weight: "400",
      style: "normal"
    }
  ],
  variable: "--font-marcellus"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <ReactLenis root>
        <body className={`${marcellusFont.variable} ${helveticaFont.variable} font-helvetica antialiased w-full min-h-screen bg-white`}>
          <NextIntlClientProvider>
            <Header />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </body>
      </ReactLenis>
    </html >
  );
}
